package Prototipo;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.BorderFactory;
import static javax.swing.SpringLayout.NORTH;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.general.DefaultPieDataset;
import Prototipo.Question;

public class Circular extends javax.swing.JFrame {

    public Circular(float p1, float p2, float p3 , float p4 , float p5) {
        initComponents();
       
        this.setLocationRelativeTo(this);
        System.out.println("porcentaje de Bipolaridad:" + p1);
        System.out.println("porcentaje de Esquizofrenia:" + p2);
        System.out.println("porcentaje de Depresion:" + p3);
        System.out.println("porcentaje de TDAH:" + p4);
        System.out.println("porcentaje de Ansiedad:" + p5);
        
        float n1 = p1;
        float n2 = p2;
        float n3 = p3;
        float n4 = p4;
        float n5 = p5; 
       
        
        DefaultPieDataset datos = new DefaultPieDataset();
        
        datos.setValue("Bipolaridad  ", n1);
        datos.setValue("Esquizofrenia  ", n2);
        datos.setValue("Depresión  ", n3);
        datos.setValue("Déficit de Atención  ", n4);
        datos.setValue("Ansiedad  ", n5);
        String b= String.format("%.1f", n1) + "%";
        String e= String.format("%.1f", n2) + "%";
        String d= String.format("%.1f", n3) + "%";
        String t= String.format("%.1f", n4) + "%";
        String a= String.format("%.1f", n5) + "%";
        jLabelB.setText(b);
        jLabelE.setText(e);
        jLabelD.setText(d);
        jLabelT.setText(t);
        jLabelA.setText(a);
        
        JFreeChart grafico_circular = ChartFactory.createPieChart(
                "Este es el porcentaje en que tiendes a presentar estos trastornos ", //nombre del grafico 
                datos, //datos
                true, //nombre de las categorias 
                true, //herramientas
                false //generacion de URL
        );
        
        ChartPanel panel = new ChartPanel(grafico_circular);
        panel.setMouseWheelEnabled(true);
        panel.setPreferredSize(new Dimension(600,500));
        
        
        Panel1.setLayout(new BorderLayout());
        Panel1.add(panel, BorderLayout.NORTH);
       
        
        pack();
        repaint();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelFondo = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabelB = new javax.swing.JLabel();
        jLabelE = new javax.swing.JLabel();
        jLabelD = new javax.swing.JLabel();
        jLabelT = new javax.swing.JLabel();
        jLabelA = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Panel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelFondo.setBackground(new java.awt.Color(163, 177, 138));
        jPanelFondo.setPreferredSize(new java.awt.Dimension(60, 0));
        jPanelFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabelB.setBackground(new java.awt.Color(255, 255, 255));
        jLabelB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelB.setForeground(new java.awt.Color(255, 0, 51));
        jLabelB.setText("bbb");

        jLabelE.setBackground(new java.awt.Color(255, 255, 255));
        jLabelE.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelE.setForeground(new java.awt.Color(51, 0, 204));
        jLabelE.setText("eee");

        jLabelD.setBackground(new java.awt.Color(255, 255, 255));
        jLabelD.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelD.setForeground(new java.awt.Color(51, 255, 0));
        jLabelD.setText("DDD");

        jLabelT.setBackground(new java.awt.Color(255, 255, 255));
        jLabelT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelT.setForeground(new java.awt.Color(255, 204, 0));
        jLabelT.setText("ttt");

        jLabelA.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelA.setForeground(new java.awt.Color(255, 0, 153));
        jLabelA.setText("aaaa");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setPreferredSize(new java.awt.Dimension(470, 30));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 28, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addComponent(jLabelB, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabelE, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabelD, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelT, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                .addComponent(jLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(98, 98, 98))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(91, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(89, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelB, javax.swing.GroupLayout.DEFAULT_SIZE, 50, Short.MAX_VALUE)
                .addComponent(jLabelE, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelA, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelD, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabelT, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        jPanelFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, 650, 50));

        Panel1.setBackground(new java.awt.Color(255, 255, 255));
        Panel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanelFondo.add(Panel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 650, 500));

        getContentPane().add(jPanelFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Circular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Circular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Circular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Circular.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Circular(0,0,0,0,0).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JPanel Panel1;
    public javax.swing.JLabel jLabelA;
    public javax.swing.JLabel jLabelB;
    public javax.swing.JLabel jLabelD;
    public javax.swing.JLabel jLabelE;
    public javax.swing.JLabel jLabelT;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanelFondo;
    // End of variables declaration//GEN-END:variables
}
