package Prototipo;

import java.awt.BorderLayout;
import javax.swing.JPanel;

public class Especialistas extends javax.swing.JPanel {

    /**
     * Creates new form Test
     */
    public Especialistas() {
        initComponents();
        
        jEsp1.setSize(220, 200);
        rsscalelabel.RSScaleLabel.setScaleLabel(jEsp1, "src/img/1.jpeg");
        jLabelEsp1.setText(StrToHtml("<p> <b>Vanessa Durán. </b> </p>"
                + "<p>Formación en terapia familiar sistémica, terapia breve centrada en soluciones, primeros auxilios psicológicos, adicciones y terapia de pareja. "));
    
        jEsp2.setSize(220, 200);
        rsscalelabel.RSScaleLabel.setScaleLabel(jEsp2, "src/img/2.jpeg");
        jLabelEsp2.setText(StrToHtml("<p> <b>Mauricio Olvera Rojo </b> </p>"
                + "<p>Estudios de posgrado, una especialidad, diplomados y seminarios desde el enfoque del psicoanálisis lacaniano para la atención clínica de Niños, Adolescentes y Adultos."));
    
        jEsp3.setSize(220, 200);
        rsscalelabel.RSScaleLabel.setScaleLabel(jEsp3, "src/img/3.jpeg");
        jLabelEsp3.setText(StrToHtml("<p> <b>Cruz Espinoza Roman </b> </p> "
                + "Psicóloga en terapia cognitivo conductual o terapia breve en atención a diferentes trastornos: ansiedad, depresión, etc. "));
        
        jEsp4.setSize(220, 200);
        rsscalelabel.RSScaleLabel.setScaleLabel(jEsp4, "src/img/4.jpeg");
        jLabelEsp4.setText(StrToHtml("<p> <b>Ernesto A. Martínez Ramírez </b> </p>"
                + "Especialista en Terapia Cognitivo Conductual y Terapias Contextuales de 3ra Generación. "));
        
        jEsp5.setSize(220, 200);
        rsscalelabel.RSScaleLabel.setScaleLabel(jEsp5, "src/img/5.jpeg");
        jLabelEsp5.setText(StrToHtml("<p> <b>Alain Leonardo Santiago González </b> </p>"
                + "Manejamos el enfoque cognitivo conductual, el cual, se basa en técnicas probadas científicamente y con sustento empírico."));

    }
    
public String StrToHtml(String texto){
        return "<html><p>" + texto + "</p></html>";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelEspecialistas = new javax.swing.JPanel();
        jPanelE1 = new javax.swing.JPanel();
        jEsp1 = new javax.swing.JLabel();
        jLabelEsp1 = new javax.swing.JLabel();
        jPanelE2 = new javax.swing.JPanel();
        jEsp2 = new javax.swing.JLabel();
        jLabelEsp2 = new javax.swing.JLabel();
        jPanelE3 = new javax.swing.JPanel();
        jEsp3 = new javax.swing.JLabel();
        jLabelEsp3 = new javax.swing.JLabel();
        jPanelE4 = new javax.swing.JPanel();
        jEsp4 = new javax.swing.JLabel();
        jLabelEsp4 = new javax.swing.JLabel();
        jPanelE5 = new javax.swing.JPanel();
        jEsp5 = new javax.swing.JLabel();
        jLabelEsp5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(163, 177, 138));
        setMaximumSize(new java.awt.Dimension(1170, 570));
        setMinimumSize(new java.awt.Dimension(1170, 570));
        setPreferredSize(new java.awt.Dimension(1170, 5745));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo.setBackground(new java.awt.Color(163, 177, 138));
        jFondo.setMinimumSize(new java.awt.Dimension(1170, 545));
        jFondo.setOpaque(false);
        jFondo.setPreferredSize(new java.awt.Dimension(1170, 545));
        jFondo.setVerifyInputWhenFocusTarget(false);
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("ESPECIALISTAS");
        jFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jPanelEspecialistas.setBackground(new java.awt.Color(163, 177, 138));
        jPanelEspecialistas.setPreferredSize(new java.awt.Dimension(1170, 410));
        jPanelEspecialistas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelE1.setBackground(new java.awt.Color(255, 255, 255));
        jPanelE1.setMinimumSize(new java.awt.Dimension(220, 250));
        jPanelE1.setPreferredSize(new java.awt.Dimension(220, 250));
        jPanelE1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEsp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/1.jpeg"))); // NOI18N
        jPanelE1.add(jEsp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        jLabelEsp1.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEsp1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelE1.add(jLabelEsp1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 200, 230));

        jPanelEspecialistas.add(jPanelE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 440));

        jPanelE2.setBackground(new java.awt.Color(255, 255, 255));
        jPanelE2.setPreferredSize(new java.awt.Dimension(220, 2500));
        jPanelE2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEsp2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/2.jpeg"))); // NOI18N
        jPanelE2.add(jEsp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        jLabelEsp2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEsp2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelE2.add(jLabelEsp2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 190));

        jPanelEspecialistas.add(jPanelE2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 220, 440));

        jPanelE3.setBackground(new java.awt.Color(255, 255, 255));
        jPanelE3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEsp3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/3.jpeg"))); // NOI18N
        jPanelE3.add(jEsp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        jLabelEsp3.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEsp3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelE3.add(jLabelEsp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 190));

        jPanelEspecialistas.add(jPanelE3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 220, 440));

        jPanelE4.setBackground(new java.awt.Color(255, 255, 255));
        jPanelE4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEsp4.setBackground(new java.awt.Color(255, 255, 255));
        jEsp4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/4.jpeg"))); // NOI18N
        jPanelE4.add(jEsp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        jLabelEsp4.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEsp4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelE4.add(jLabelEsp4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 190));

        jPanelEspecialistas.add(jPanelE4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 220, 440));

        jPanelE5.setBackground(new java.awt.Color(255, 255, 255));
        jPanelE5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEsp5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/5.jpeg"))); // NOI18N
        jPanelE5.add(jEsp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        jLabelEsp5.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEsp5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelE5.add(jLabelEsp5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 190));

        jPanelEspecialistas.add(jPanelE5, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 10, 220, 440));

        jFondo.add(jPanelEspecialistas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1150, 450));

        jPanel1.setBackground(new java.awt.Color(192, 189, 44));
        jFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1170, 10));

        add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 545));
    }// </editor-fold>//GEN-END:initComponents
 private void ShowPanel(JPanel p){
        p.setSize(1170, 410);
        jPanelEspecialistas.removeAll();
        jPanelEspecialistas.add(p, BorderLayout.CENTER);
        jPanelEspecialistas.revalidate();
        jPanelEspecialistas.repaint();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jEsp1;
    private javax.swing.JLabel jEsp2;
    private javax.swing.JLabel jEsp3;
    private javax.swing.JLabel jEsp4;
    private javax.swing.JLabel jEsp5;
    public javax.swing.JPanel jFondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEsp1;
    private javax.swing.JLabel jLabelEsp2;
    private javax.swing.JLabel jLabelEsp3;
    private javax.swing.JLabel jLabelEsp4;
    private javax.swing.JLabel jLabelEsp5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelE1;
    private javax.swing.JPanel jPanelE2;
    private javax.swing.JPanel jPanelE3;
    private javax.swing.JPanel jPanelE4;
    private javax.swing.JPanel jPanelE5;
    public javax.swing.JPanel jPanelEspecialistas;
    // End of variables declaration//GEN-END:variables
}
