
package Prototipo;

import java.awt.BorderLayout;
import javax.swing.JPanel;

public class Especialista1 extends javax.swing.JPanel {

    /**
     * Creates new form Test
     */
    public Especialista1() {
        initComponents();
        
        //jEspecialista.setSize(280, 250);
        //rsscalelabel.RSScaleLabel.setScaleLabel(jEspecialista, "src/img/Ansiedad.jpg");
        jLabelEspecialista.setText(StrToHtml("¡Hola! Mi nombre es Vanessa Durán, soy psicoterapeuta. Tengo una "
                + "formación en terapia familiar sistémica, terapia breve centrada en soluciones, primeros auxilios "
                + "psicológicos, adicciones y terapia de pareja. El objetivo de la terapia es que lograr generar "
                + "cambios deseados y/o positivos (metas terapéuticas) en la vida de quienes buscan iniciar un proceso"
                + " de psicoterapia.\n" +
"                            \n" +
"                            <br>\n" +
"                            <b>Número de contacto </b></p>\n" +
"                            <ul>\n" +
"                                <li><ul>800 953 1985 </li> </ul>\n" +
"                            </ul>\n" +
"                            <br>" +
"                           <b>Ubicacion</b></p>\n" +
"                            <ul>\n" +
"                                <li>Pancho López 111, Col. Benito Juarez.Primer piso 57000 Nezahualcóyotl\n" +
"                            </ul>\n" +
"                            \n" +
"                            <br>\n" +
"                            <b>Costos</b></p>\n" +
                "            <ul>\n" +
"                                <li>$500 por sesión\n" +
"                            </ul>\n" +
"                            \n" +
"                            <br>\n" +
"                            <b>Experiencia</b></p>\n" +
"                            <ul>\n" +
"                                <li>Adicciones.</li>\n" +
"                                <li>Ansiedad.</li>\n" +
"                                <li>Depresión.</li>\n" +
"                                <li>Autoestima.</li>\n" +
"                                <li>Codependencia.</li>\n" +
"                                <li>Control de la ira.</li>\n" +
                "                <li>Duelo.</li>\n" +
"                                <li>Estrés.</li>\n" +
"                                <li>Insomio y trastornos del sueño.</li>\n" +
"                                <li>Pensamientos suicidas.</li>\n" +
"                                <li>Terapia para hombres.</li>\n" +
"                                <li>Terapia para mujeres.</li>\n" +
                "                <li>Trastorno de estrés postraumático (TEPT).</li>\n" +
"                                <li>Trastorno obsesivo-compulsivo (TOC).</li>\n" +
"                                <li>Trastornos de la personalidad.</li>\n" +
"                            </ul>"
        
        
        
        ));
    
        
    }
    
public String StrToHtml(String texto){
        return "<html><p>" + texto + "</p></html>";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        jEspecialista = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLinea = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabelEspecialista = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(163, 177, 138));
        setMaximumSize(new java.awt.Dimension(1170, 570));
        setMinimumSize(new java.awt.Dimension(1170, 570));
        setPreferredSize(new java.awt.Dimension(1170, 5745));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo.setBackground(new java.awt.Color(163, 177, 138));
        jFondo.setMinimumSize(new java.awt.Dimension(1170, 545));
        jFondo.setOpaque(false);
        jFondo.setPreferredSize(new java.awt.Dimension(1170, 545));
        jFondo.setVerifyInputWhenFocusTarget(false);
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEspecialista.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/1.jpeg"))); // NOI18N
        jFondo.add(jEspecialista, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 120, 300, 410));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Vanessa Janeth Durán Patiño");
        jFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLinea.setBackground(new java.awt.Color(192, 189, 44));
        jFondo.add(jLinea, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1170, 10));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabelEspecialista.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEspecialista.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanel1.add(jLabelEspecialista, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 790, 750));

        jScrollPane1.setViewportView(jPanel1);

        jFondo.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 820, 440));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Psicoterapeuta, Lic. en Psicología");
        jFondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 100, -1, -1));

        add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 545));
    }// </editor-fold>//GEN-END:initComponents
 private void ShowPanel(JPanel p){
        p.setSize(1170, 410);
       
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jEspecialista;
    public javax.swing.JPanel jFondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelEspecialista;
    private javax.swing.JPanel jLinea;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
