/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Prototipo;

import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author maylo
 */
public class Informacion extends javax.swing.JPanel {

    /**
     * Creates new form Test
     */
    public Informacion() {
        initComponents();
        
        jAnsiedad.setSize(280, 250);
        rsscalelabel.RSScaleLabel.setScaleLabel(jAnsiedad, "src/img/Ansiedad.jpg");
        jLabelAnsiedad.setText(StrToHtml("La ansiedad es un sentimiento universal experimentado por todos en "
                + "ciertos momentos, que funciona como un mecanismo de preparación del cuerpo ante eventos significativos."));
    
        jDepresion.setSize(280, 250);
        rsscalelabel.RSScaleLabel.setScaleLabel(jDepresion, "src/img/Depresion.jpg");
        jLabelDepresion.setText(StrToHtml("El trastorno depresivo se distingue por un estado emocional melancólico de "
                + "una magnitud o duración suficiente para perturbar la operatividad."));
    
        jBipolar.setSize(280, 250);
        rsscalelabel.RSScaleLabel.setScaleLabel(jBipolar, "src/img/Bipolar.jpg");
        jLabelBipolar.setText(StrToHtml("El trastorno bipolar o bipolaridad, se caracteriza por ser "
                + "una afección psiquiátrica que compromete severamente la estabilidad emocional y mental de quienes la "
                + "padecen."));
        
        jEsquizo.setSize(280, 250);
        rsscalelabel.RSScaleLabel.setScaleLabel(jEsquizo, "src/img/Esquizofrenia.jpeg");
        jLabelEsquizo.setText(StrToHtml("La esquizofrenia representa un trastorno psiquiátrico severo, caracterizado por "
                + "una interpretación distorsionada de la realidad por parte de quienes lo padecen."));
        
        jTda.setSize(280, 250);
        rsscalelabel.RSScaleLabel.setScaleLabel(jTda, "src/img/TDAH.jpeg");
        jLabelTda.setText(StrToHtml("El TDAH es un trastorno neuroconductual que provoca desórdenes en el comportamiento "
                + "derivados de una falta de atención apropiada y/o hiperactividad e impulsividad."));

    }
    
public String StrToHtml(String texto){
        return "<html><p>" + texto + "</p></html>";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFondo = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelTrastornos = new javax.swing.JPanel();
        jPanelA = new javax.swing.JPanel();
        jAnsiedad = new javax.swing.JLabel();
        ANSIEDAD = new javax.swing.JLabel();
        jLabelAnsiedad = new javax.swing.JLabel();
        jPanelD = new javax.swing.JPanel();
        jDepresion = new javax.swing.JLabel();
        DEPRESION = new javax.swing.JLabel();
        jLabelDepresion = new javax.swing.JLabel();
        jPanelB = new javax.swing.JPanel();
        jBipolar = new javax.swing.JLabel();
        BIPOLAR = new javax.swing.JLabel();
        jLabelBipolar = new javax.swing.JLabel();
        jPanelE = new javax.swing.JPanel();
        jEsquizo = new javax.swing.JLabel();
        ESQUIZO = new javax.swing.JLabel();
        jLabelEsquizo = new javax.swing.JLabel();
        jPanelT = new javax.swing.JPanel();
        jTda = new javax.swing.JLabel();
        TDA = new javax.swing.JLabel();
        jLabelTda = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(163, 177, 138));
        setMaximumSize(new java.awt.Dimension(1170, 570));
        setMinimumSize(new java.awt.Dimension(1170, 570));
        setPreferredSize(new java.awt.Dimension(1170, 5745));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jFondo.setBackground(new java.awt.Color(163, 177, 138));
        jFondo.setMinimumSize(new java.awt.Dimension(1170, 545));
        jFondo.setOpaque(false);
        jFondo.setPreferredSize(new java.awt.Dimension(1170, 545));
        jFondo.setVerifyInputWhenFocusTarget(false);
        jFondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("INFORMACIÓN");
        jFondo.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        jPanelTrastornos.setBackground(new java.awt.Color(163, 177, 138));
        jPanelTrastornos.setPreferredSize(new java.awt.Dimension(1170, 410));
        jPanelTrastornos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelA.setBackground(new java.awt.Color(255, 255, 255));
        jPanelA.setMinimumSize(new java.awt.Dimension(220, 250));
        jPanelA.setPreferredSize(new java.awt.Dimension(220, 250));
        jPanelA.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jAnsiedad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Ansiedad.jpg"))); // NOI18N
        jPanelA.add(jAnsiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        ANSIEDAD.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ANSIEDAD.setText("ANSIEDAD");
        ANSIEDAD.setToolTipText("");
        jPanelA.add(ANSIEDAD, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabelAnsiedad.setBackground(new java.awt.Color(255, 255, 255));
        jLabelAnsiedad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelA.add(jLabelAnsiedad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 190));

        jPanelTrastornos.add(jPanelA, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 220, 440));

        jPanelD.setBackground(new java.awt.Color(255, 255, 255));
        jPanelD.setPreferredSize(new java.awt.Dimension(220, 2500));
        jPanelD.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jDepresion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Depresion.jpg"))); // NOI18N
        jPanelD.add(jDepresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        DEPRESION.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        DEPRESION.setText("DEPRESIÓN");
        DEPRESION.setToolTipText("");
        jPanelD.add(DEPRESION, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabelDepresion.setBackground(new java.awt.Color(255, 255, 255));
        jLabelDepresion.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelD.add(jLabelDepresion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 190));

        jPanelTrastornos.add(jPanelD, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 220, 440));

        jPanelB.setBackground(new java.awt.Color(255, 255, 255));
        jPanelB.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jBipolar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Bipolar.jpg"))); // NOI18N
        jPanelB.add(jBipolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        BIPOLAR.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BIPOLAR.setText("BIPOLARIDAD");
        BIPOLAR.setToolTipText("");
        jPanelB.add(BIPOLAR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jLabelBipolar.setBackground(new java.awt.Color(255, 255, 255));
        jLabelBipolar.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelB.add(jLabelBipolar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 190));

        jPanelTrastornos.add(jPanelB, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 10, 220, 440));

        jPanelE.setBackground(new java.awt.Color(255, 255, 255));
        jPanelE.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEsquizo.setBackground(new java.awt.Color(255, 255, 255));
        jEsquizo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/esquizofrenia.jpeg"))); // NOI18N
        jPanelE.add(jEsquizo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        ESQUIZO.setBackground(new java.awt.Color(255, 255, 255));
        ESQUIZO.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ESQUIZO.setText("ESQUIZOFRENIA");
        ESQUIZO.setToolTipText("");
        jPanelE.add(ESQUIZO, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));

        jLabelEsquizo.setBackground(new java.awt.Color(255, 255, 255));
        jLabelEsquizo.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelE.add(jLabelEsquizo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 190));

        jPanelTrastornos.add(jPanelE, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 10, 220, 440));

        jPanelT.setBackground(new java.awt.Color(255, 255, 255));
        jPanelT.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/TDAH.jpeg"))); // NOI18N
        jPanelT.add(jTda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 200));

        TDA.setBackground(new java.awt.Color(255, 255, 255));
        TDA.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TDA.setText("TDAH");
        TDA.setToolTipText("");
        jPanelT.add(TDA, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabelTda.setBackground(new java.awt.Color(255, 255, 255));
        jLabelTda.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jPanelT.add(jLabelTda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, 200, 190));

        jPanelTrastornos.add(jPanelT, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 10, 220, 440));

        jFondo.add(jPanelTrastornos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 1150, 450));

        jPanel1.setBackground(new java.awt.Color(192, 189, 44));
        jFondo.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1170, 10));

        add(jFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 545));
    }// </editor-fold>//GEN-END:initComponents
 private void ShowPanel(JPanel p){
        p.setSize(1170, 410);
        jPanelTrastornos.removeAll();
        jPanelTrastornos.add(p, BorderLayout.CENTER);
        jPanelTrastornos.revalidate();
        jPanelTrastornos.repaint();
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ANSIEDAD;
    private javax.swing.JLabel BIPOLAR;
    private javax.swing.JLabel DEPRESION;
    private javax.swing.JLabel ESQUIZO;
    private javax.swing.JLabel TDA;
    private javax.swing.JLabel jAnsiedad;
    private javax.swing.JLabel jBipolar;
    private javax.swing.JLabel jDepresion;
    private javax.swing.JLabel jEsquizo;
    public javax.swing.JPanel jFondo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelAnsiedad;
    private javax.swing.JLabel jLabelBipolar;
    private javax.swing.JLabel jLabelDepresion;
    private javax.swing.JLabel jLabelEsquizo;
    private javax.swing.JLabel jLabelTda;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanelA;
    private javax.swing.JPanel jPanelB;
    private javax.swing.JPanel jPanelD;
    private javax.swing.JPanel jPanelE;
    private javax.swing.JPanel jPanelT;
    public javax.swing.JPanel jPanelTrastornos;
    private javax.swing.JLabel jTda;
    // End of variables declaration//GEN-END:variables
}
