/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Prototipo;

/**
 *
 * @author maylo
 */
public class Inicio extends javax.swing.JPanel {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        
        Logo1.setSize(230, 230);
        rsscalelabel.RSScaleLabel.setScaleLabel(Logo1, "src/img/Logo1.png");
        Logo2.setSize(200, 200);
        rsscalelabel.RSScaleLabel.setScaleLabel(Logo2, "src/img/Logo2.png");
        
        titulo.setText(StrToHtml("PROTOTIPO DE UN SISTEMA BASADO EN CONOCIMIENTOS PARA LA DETECCIÓN DE TRASTORNOS MENTALES"));
        texto.setText(StrToHtml("Los trastornos mentales son condiciones que afectan la forma en que una persona piensa, siente, "
                + "se comporta o interactúa con los demás. Pueden surgir de una variedad de factores, incluidos los genéticos, "
                + "biológicos, ambientales y psicológicos. Algunos trastornos comunes incluyen la depresión, la ansiedad, "
                + "la esquizofrenia y el trastorno bipolar.Estos trastornos pueden tener síntomas diferentes y afectar a las personas "
                + "de manera única. El tratamiento varía según el trastorno y puede incluir terapia,\n" +
"             medicación y apoyo social. Es importante buscar ayuda profesional si se experimentan síntomas de un trastorno mental para recibir el tratamiento adecuado \n" +
"             y mejorar la calidad de vida.</p>\n\n" +
"\n" +

"\n" +
"        <p>\nEl objetivo de este test es el diagnostico de los diferentes trastornos mentales como: Depresión, Ansiedad, Esquizofrenia, Bipolaridad y TDAH"));
        
    img.setSize(280, 285);
    rsscalelabel.RSScaleLabel.setScaleLabel(img, "src/img/Imagen.png");
        
    }
    
    

    public String StrToHtml(String texto){
        return "<html><p>" + texto + "</p></html>";
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Logo1 = new javax.swing.JLabel();
        Logo2 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        img = new javax.swing.JLabel();
        texto = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setBackground(new java.awt.Color(163, 177, 138));
        setMinimumSize(new java.awt.Dimension(1160, 570));
        setPreferredSize(new java.awt.Dimension(1170, 570));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Logo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo1.png"))); // NOI18N
        add(Logo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 230));

        Logo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/Logo1.png"))); // NOI18N
        add(Logo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 0, 230, 230));

        titulo.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        titulo.setForeground(new java.awt.Color(0, 0, 0));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 630, 100));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Ingenieria en Sistemas Inteligentes");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, 540, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Centro Universitario UAEM Nezahualcóyotl");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, 540, 30));
        add(img, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 320, 310));

        texto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        texto.setForeground(new java.awt.Color(0, 0, 0));
        add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 810, 320));

        jPanel1.setBackground(new java.awt.Color(192, 189, 44));
        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 215, 1170, 10));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Logo1;
    private javax.swing.JLabel Logo2;
    private javax.swing.JLabel img;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel texto;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
